version: "3.9"

networks:
  idr-app-network:
    external: true
  local:
    external: false

services:
  app:
    image: idr-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idr-app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idr-app.rule=Host(`app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.idr-app.entrypoints=websecure"
      - "traefik.http.routers.idr-app.tls.domains[0].main=app.pb.utfpr.edu.br"
      - "traefik.http.routers.idr-app.tls.domains[0].sans=*.app.pb.utfpr.edu.br"
      - "traefik.http.routers.idr-app.tls.certresolver=letsencrypt"
    ports:
      - "8200:80"
    networks:
      - idr-app-network