export type { ICreateProperty } from './createProperty'
export type { IDeleteProperty } from './deleteProperty'
export type { IGetProperties } from './getProperties'
export type { IGetProperty } from './getProperty'
export type { IUpdateProperty } from './updateProperty'
